/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import models.MySQL;

/**
 *
 * @author sanka
 */
public class CompletePayments extends javax.swing.JFrame {

    /**
     * Creates new form CompletePayments
     */
    private static int invoice;

    public CompletePayments(java.awt.Frame parent, boolean modal, int invoiceID) {
        invoice = invoiceID;
        initComponents();
        loadData();
    }

    private void loadData() {

        nameField.setEnabled(false);
        nicField.setEnabled(false);
        dateField.setEnabled(false);
        locationField.setEnabled(false);
        discountField.setEnabled(false);
        advancementField.setEnabled(false);
        totalPriceField.setEnabled(false);
        dueAmountField.setEnabled(false);
        invoiceIDField.setEnabled(false);
        paidAmount.setEnabled(false);

        try {
            ResultSet rs = MySQL.execute("SELECT * FROM invoice "
                    + "INNER JOIN customer ON customer.mobile = invoice.customer_mobile "
                    + "INNER JOIN location ON location.id = customer.location_id "
                    + "WHERE invoice.invoice_id = " + invoice);

            if (rs.next()) {
                System.out.println(rs.getString("name"));
                nameField.setText(rs.getString("name"));
                nicField.setText(rs.getString("nic"));
                dateField.setText(rs.getString("date"));
                locationField.setText(rs.getString("location_name"));
                discountField.setText(rs.getString("discount"));

                advancementField.setText(rs.getString("advance_payment"));
                paidAmount.setText(rs.getString("payment_amount"));
                totalPriceField.setText(rs.getString("total_price"));
                subTotal.setText(rs.getString("subtotal"));
                dueAmountField.setText(String.valueOf(rs.getDouble("subtotal") - rs.getDouble("payment_amount")));
            }

        } catch (Exception e) {
            System.out.println(e);
        }

        invoiceIDField.setText(String.valueOf(invoice));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        invoiceIDField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        nicField = new javax.swing.JTextField();
        dateField = new javax.swing.JTextField();
        locationField = new javax.swing.JTextField();
        discountField = new javax.swing.JTextField();
        advancementField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        totalPriceField = new javax.swing.JTextField();
        dueAmountField = new javax.swing.JTextField();
        proceedBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        paidAmount = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        subTotal = new javax.swing.JTextField();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Complete Payment");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 18, -1, -1));

        jLabel3.setText("Invoice ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));
        jPanel1.add(invoiceIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 153, -1));

        jLabel1.setText("Customer Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jLabel4.setText("Customer NIC");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        jLabel5.setText("Advanced Date");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        jLabel6.setText("Location");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        jLabel7.setText("Discount");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        jLabel8.setText("Advancement");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, -1, -1));
        jPanel1.add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 153, -1));
        jPanel1.add(nicField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 153, -1));
        jPanel1.add(dateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 153, -1));
        jPanel1.add(locationField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 153, -1));
        jPanel1.add(discountField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 153, -1));
        jPanel1.add(advancementField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 153, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Sub Total");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 627, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Total Due Amount");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, -1, -1));
        jPanel1.add(totalPriceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 153, -1));

        dueAmountField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(dueAmountField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 153, -1));

        proceedBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        proceedBtn.setText("Proceed Payment");
        proceedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proceedBtnActionPerformed(evt);
            }
        });
        jPanel1.add(proceedBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 570, 180, 40));

        jLabel10.setText("Payment Method");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 510, 100, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 168, -1));

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 620, -1, -1));
        jPanel1.add(paidAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 153, -1));

        jLabel13.setText("Paid Amount");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Total Price");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, -1, -1));
        jPanel1.add(subTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 150, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Cash");
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, 70, 30));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Card");
        jPanel1.add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 70, 30));

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("Online Payment");
        jPanel1.add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 140, 30));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Bank Deposit");
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 120, 30));

        jLabel15.setText("Pay amount");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 73, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void proceedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proceedBtnActionPerformed

        try {

            System.out.println(buttonGroup1.getSelection());

            if (jTextField1.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please Enter A Payment amount", "Empty Payment Field", JOptionPane.ERROR_MESSAGE);
            } else {
                if (buttonGroup1.getSelection() != null) {
                    double Total_amount = Double.parseDouble(totalPriceField.getText());
                    double paid_amount = Double.parseDouble(paidAmount.getText());
                    double payAmount = Double.parseDouble(jTextField1.getText());
                    double advancedPayment = Double.parseDouble(advancementField.getText());
                    double subTotalAmount = Double.parseDouble(subTotal.getText());
                    int paymentMethodSelecetd = 0;

//                payment Assign
                    if (jRadioButton2.isSelected()) {
                        paymentMethodSelecetd = 1;
                    } else if (jRadioButton3.isSelected()) {
                        paymentMethodSelecetd = 2;
                    } else if (jRadioButton4.isSelected()) {
                        paymentMethodSelecetd = 3;
                    } else if (jRadioButton1.isSelected()) {
                        paymentMethodSelecetd = 4;
                    }

                    double payment = paid_amount + payAmount;

                    double ballence = (advancedPayment + Total_amount) - payment;

                    double newtotalPayment = subTotalAmount - (paid_amount + payAmount);

                    // payment history
                    LocalDateTime now = LocalDateTime.now();
                    DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                    String curruntDay = now.format(dateFormatter);
                    DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm:ss");
                    String curruntTime = now.format(timeFormatter);

                    MySQL.execute("INSERT INTO `advance_payment_history` (`invoice_invoice_id`,`paid_amount`,`date`,`time`,`payment_method`) VALUES ('" + invoice + "','" + payAmount + "','" + curruntDay + "','" + curruntTime + "','" + paymentMethodSelecetd + "') ");
                    MySQL.execute("UPDATE `invoice` SET `total_price` = '" + newtotalPayment + "'  WHERE `invoice_id` = '" + invoice + "' ");

                    if (ballence <= 0.00) {
                        System.out.println("Payment Complete");
                        MySQL.execute("UPDATE `invoice` SET `payment_status_id` = 2 , `payment_amount` ='" + payment + "'  WHERE invoice_id = " + invoice);
                    } else {
                        System.out.println("Payment not complete");
                        MySQL.execute("UPDATE `invoice` SET  `payment_amount` = '" + payment + "'  WHERE invoice_id = " + invoice);
                    }
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Please Select a Payment Method", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }

        } catch (Exception e) {
            System.out.println(e);
        }


    }//GEN-LAST:event_proceedBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // close btn
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompletePayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompletePayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompletePayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompletePayments.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField advancementField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField dateField;
    private javax.swing.JTextField discountField;
    private javax.swing.JTextField dueAmountField;
    private javax.swing.JTextField invoiceIDField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField locationField;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField nicField;
    private javax.swing.JTextField paidAmount;
    private javax.swing.JButton proceedBtn;
    private javax.swing.JTextField subTotal;
    private javax.swing.JTextField totalPriceField;
    // End of variables declaration//GEN-END:variables
}
